apiVersion: v1
kind: ServiceAccount
metadata:
  name: cm-orchestrator
  namespace: cm-games
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cm-pod-manager
  namespace: cm-games
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "create", "delete", "watch"]
  - apiGroups: ["networking.k8s.io"]
    resources: ["ingresses"]
    verbs: ["get", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cm-orchestrator-binding
  namespace: cm-games
subjects:
  - kind: ServiceAccount
    name: cm-orchestrator
    namespace: cm-games
roleRef:
  kind: Role
  name: cm-pod-manager
  apiGroup: rbac.authorization.k8s.io
