apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cm-web-app-ingress
  namespace: cm-games
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - cm.jofriel.fyi
      secretName: cm-game-tls
  rules:
    - host: cm.jofriel.fyi
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cm-web-app
                port:
                  number: 3000
