name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-game-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./docker/game
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cm0102-server:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

  build-web-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v3

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v5
        with:
          context: ./web-app
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/cm-web-app:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
